language: php
php:
  - 7.1
before_install:
  - composer selfupdate
install:
  - composer install --prefer-dist --no-interaction $COMPOSER_FLAGS
script:
  - phpunit --configuration phpunit.xml --coverage-text
notifications:
  email: snebes+github@gmail.com
